#!/usr/bin/env python3
"""skills-sync.py — canonical skill tree and its tool-scope mirrors (KDD-0020).

Canonical source of every skill is `.agents/skills/` (KDD-0020, 2026-08-30).
Kimi Code reads `.kimi-code/skills/` and Claude Code reads `.claude/skills/`;
neither tool follows a foreign directory, so each gets a mirror.

Mirrors are real copies, not symlinks: this repository has a recorded
flattened-symlink failure class (PILOT-DSH-IMPL-001, Morpheus Phase A survey),
and a copy survives export and archiving where a link does not.

ARCHIFY EXCEPTION: `archify` is a Node CLI (168 files, 6.8 MB) invoked by path,
not a prompt skill loaded into a model's context. Mirroring it three times buys
no review value and triples its footprint, so the mirrors carry a pointer stub
instead. The stub is a plain document: it is never given a catalog record and
never carries a `canonical_location` key, because every catalog
`canonical_location` enters validate.py's CAT-08 `canon_locations` set and a
raw-path relation target matching one is a graded failure.

Usage:
    python3 scripts/skills_sync.py --check    # verify; exit 1 on drift
    python3 scripts/skills_sync.py --write    # rebuild the mirrors

Stdlib only, deterministic, read-only under --check. No network, no host access.
"""

import filecmp
import os
import shutil
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

CANONICAL = ".agents/skills"
MIRRORS = (".kimi-code/skills", ".claude/skills")

# Skills mirrored as a pointer stub rather than a full copy (see module docstring).
STUB_ONLY = ("archify",)

STUB_TEMPLATE = """---
name: %(name)s
description: "Pointer stub. The %(name)s skill is canonical at %(canonical)s/%(name)s/ and is not mirrored here; see that directory for the skill itself."
---

# %(name)s — pointer stub

This is not the skill. `%(name)s` is a Node CLI invoked by path, not a prompt
skill loaded into context, so it is kept in one place only.

**Canonical location:** `%(canonical)s/%(name)s/`

Read `%(canonical)s/%(name)s/SKILL.md` for the skill, and run it from the
canonical directory. Do not edit this stub; it is generated by
`scripts/skills_sync.py` and overwritten on the next sync.
"""


def _skills(path):
    """Immediate child directories of path, sorted. Empty list if absent."""
    full = os.path.join(ROOT, path)
    if not os.path.isdir(full):
        return []
    return sorted(d for d in os.listdir(full)
                  if os.path.isdir(os.path.join(full, d)))


def _files(path):
    """Repo-relative file paths under path, sorted, excluding caches."""
    full = os.path.join(ROOT, path)
    out = []
    for base, dirs, names in os.walk(full):
        dirs[:] = sorted(d for d in dirs
                         if d not in ("__pycache__", "node_modules", ".git"))
        for n in sorted(names):
            if n.endswith(".pyc"):
                continue
            out.append(os.path.relpath(os.path.join(base, n), full))
    return sorted(out)


def _stub_text(name):
    return STUB_TEMPLATE % {"name": name, "canonical": CANONICAL}


def plan():
    """Return (problems, canonical_skill_names). problems is a list of strings."""
    problems = []
    canon = _skills(CANONICAL)
    if not canon:
        problems.append("[SY-3] canonical skill tree %s is missing or empty" % CANONICAL)
        return problems, canon

    for mirror in MIRRORS:
        have = set(_skills(mirror))
        want = set(canon)
        for extra in sorted(have - want):
            problems.append("[SY-3] EXTRA %s/%s — not in %s" % (mirror, extra, CANONICAL))
        for missing in sorted(want - have):
            problems.append("[SY-3] MISSING %s/%s" % (mirror, missing))

        for name in canon:
            if name not in have:
                continue
            if name in STUB_ONLY:
                stub = os.path.join(ROOT, mirror, name, "SKILL.md")
                only = _files(os.path.join(mirror, name))
                if only != ["SKILL.md"]:
                    problems.append("[SY-3] DRIFT %s/%s — stub-only skill must contain "
                                    "exactly SKILL.md, found %d file(s)" % (mirror, name, len(only)))
                    continue
                with open(stub, encoding="utf-8") as fh:
                    if fh.read() != _stub_text(name):
                        problems.append("[SY-3] DRIFT %s/%s/SKILL.md — stub text does not match "
                                        "the generated form" % (mirror, name))
                continue

            src_files = _files(os.path.join(CANONICAL, name))
            dst_files = _files(os.path.join(mirror, name))
            if src_files != dst_files:
                for f in sorted(set(src_files) - set(dst_files)):
                    problems.append("[SY-3] MISSING %s/%s/%s" % (mirror, name, f))
                for f in sorted(set(dst_files) - set(src_files)):
                    problems.append("[SY-3] EXTRA %s/%s/%s" % (mirror, name, f))
            for f in sorted(set(src_files) & set(dst_files)):
                a = os.path.join(ROOT, CANONICAL, name, f)
                b = os.path.join(ROOT, mirror, name, f)
                if not filecmp.cmp(a, b, shallow=False):
                    problems.append("[SY-3] DRIFT %s/%s/%s" % (mirror, name, f))
    return problems, canon


def write():
    canon = _skills(CANONICAL)
    if not canon:
        print("refusing to write: canonical tree %s is missing or empty" % CANONICAL,
              file=sys.stderr)
        return 1
    for mirror in MIRRORS:
        mroot = os.path.join(ROOT, mirror)
        for extra in set(_skills(mirror)) - set(canon):
            shutil.rmtree(os.path.join(mroot, extra))
            print("  removed  %s/%s" % (mirror, extra))
        for name in canon:
            dst = os.path.join(mroot, name)
            if os.path.isdir(dst):
                shutil.rmtree(dst)
            if name in STUB_ONLY:
                os.makedirs(dst, exist_ok=True)
                with open(os.path.join(dst, "SKILL.md"), "w", encoding="utf-8") as fh:
                    fh.write(_stub_text(name))
                print("  stubbed  %s/%s" % (mirror, name))
            else:
                shutil.copytree(os.path.join(ROOT, CANONICAL, name), dst,
                                ignore=shutil.ignore_patterns("__pycache__", "*.pyc",
                                                              "node_modules", ".git"))
                print("  copied   %s/%s" % (mirror, name))
    print("skills-sync: %d skills, %d mirrors in sync" % (len(canon), len(MIRRORS)))
    return 0


def main(argv):
    if argv == ["--write"]:
        return write()
    if argv == ["--check"]:
        problems, canon = plan()
        for p in problems:
            print(p)
        if problems:
            print("skills-sync: %d problem(s) — repair: python3 scripts/skills_sync.py --write"
                  % len(problems))
            return 1
        print("skills-sync: %d skills, %d mirrors in sync (%s stub-only)"
              % (len(canon), len(MIRRORS), ", ".join(STUB_ONLY)))
        return 0
    print("usage: python3 scripts/skills_sync.py [--check | --write]", file=sys.stderr)
    return 2


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
